services:
  pg:
    container_name: pg_container
    image: postgres:14.1-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - "./data/initdb/:/docker-entrypoint-initdb.d/"
    networks:
      - nunet

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - pg
    networks:
      - nunet

  flask-app:
    container_name: flask_container
    image: nupgsql/flask:latest
    ports:
      - "5000:5000"
    depends_on:
      - pg
    volumes:
      - ./app:/app
    environment:
      FLASK_APP: app/app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres@pg:5432/postgres
      SQLALCHEMY_DATABASE_URI: postgresql://postgres@pg:5432/postgres
    networks:
      - nunet

networks:
  nunet:
    driver: bridge
